select * from CONFIGURATION  where configuration_key in (
        'MODULE_PAYMENT_DIRBANKZA_STATUS',
        'MODULE_PAYMENT_DIRBANKZA_ZONE',
        'MODULE_PAYMENT_DIRBANKZA_SORT_ORDER',
        'MODULE_PAYMENT_DIRBANKZA_ACCNUM',
        'MODULE_PAYMENT_DIRBANKZA_ACCNAM',
        'MODULE_PAYMENT_DIRBANKZA_BANKNAM',
        'MODULE_PAYMENT_DIRBANKZA_BANKCODE',
        'MODULE_PAYMENT_DIRBANKZA_ORDER_STATUS_ID',
        );

delete from CONFIGURATION  where configuration_key in (
        'MODULE_PAYMENT_DIRBANKZA_STATUS',
        'MODULE_PAYMENT_DIRBANKZA_ZONE',
        'MODULE_PAYMENT_DIRBANKZA_SORT_ORDER',
        'MODULE_PAYMENT_DIRBANKZA_ACCNUM',
        'MODULE_PAYMENT_DIRBANKZA_ACCNAM',
        'MODULE_PAYMENT_DIRBANKZA_BANKNAM',
        'MODULE_PAYMENT_DIRBANKZA_BANKCODE',
        'MODULE_PAYMENT_DIRBANKZA_ORDER_STATUS_ID',
        );
