select * from CONFIGURATION  where configuration_key in (
'MODULE_PAYMENT_DIRBANKAUS_STATUS',
'MODULE_PAYMENT_DIRBANKAUS_ZONE',
'MODULE_PAYMENT_DIRBANKAUS_SORT_ORDER',
'MODULE_PAYMENT_DIRBANKAUS_BSB',
'MODULE_PAYMENT_DIRBANKAUS_ACCNUM',
'MODULE_PAYMENT_DIRBANKAUS_ACCNAM',
'MODULE_PAYMENT_DIRBANKAUS_SWIFT',
'MODULE_PAYMENT_DIRBANKAUS_BANKNAM',
'MODULE_PAYMENT_DIRBANKAUS_ORDER_STATUS_ID',
'MODULE_PAYMENT_DIRBANKAUS_ADDRESS',
'MODULE_PAYMENT_DIRBANKAUS_PAYABLE');

delete from CONFIGURATION  where configuration_key in (
'MODULE_PAYMENT_DIRBANKAUS_STATUS',
'MODULE_PAYMENT_DIRBANKAUS_ZONE',
'MODULE_PAYMENT_DIRBANKAUS_SORT_ORDER',
'MODULE_PAYMENT_DIRBANKAUS_BSB',
'MODULE_PAYMENT_DIRBANKAUS_ACCNUM',
'MODULE_PAYMENT_DIRBANKAUS_ACCNAM',
'MODULE_PAYMENT_DIRBANKAUS_SWIFT',
'MODULE_PAYMENT_DIRBANKAUS_BANKNAM',
'MODULE_PAYMENT_DIRBANKAUS_ORDER_STATUS_ID',
'MODULE_PAYMENT_DIRBANKAUS_ADDRESS',
'MODULE_PAYMENT_DIRBANKAUS_PAYABLE');