select * from CONFIGURATION  where configuration_key in (
'MODULE_PAYMENT_DIRBANKUSA_STATUS', 
'MODULE_PAYMENT_DIRBANKUSA_ZONE', 
'MODULE_PAYMENT_DIRBANKUSA_SORT_ORDER', 
'MODULE_PAYMENT_DIRBANKUSA_ROUTING', 
'MODULE_PAYMENT_DIRBANKUSA_ACCNUM', 
'MODULE_PAYMENT_DIRBANKUSA_ACCNAM',  
'MODULE_PAYMENT_DIRBANKUSA_BANKNAM', 
'MODULE_PAYMENT_DIRBANKUSA_ORDER_STATUS_ID');

delete from CONFIGURATION  where configuration_key in (
'MODULE_PAYMENT_DIRBANKUSA_STATUS', 
'MODULE_PAYMENT_DIRBANKUSA_ZONE', 
'MODULE_PAYMENT_DIRBANKUSA_SORT_ORDER', 
'MODULE_PAYMENT_DIRBANKUSA_ROUTING', 
'MODULE_PAYMENT_DIRBANKUSA_ACCNUM', 
'MODULE_PAYMENT_DIRBANKUSA_ACCNAM',  
'MODULE_PAYMENT_DIRBANKUSA_BANKNAM', 
'MODULE_PAYMENT_DIRBANKUSA_ORDER_STATUS_ID');