select * from CONFIGURATION  where configuration_key in (
            'MODULE_PAYMENT_DIRBANKNZ_STATUS',
            'MODULE_PAYMENT_DIRBANKNZ_ZONE',
            'MODULE_PAYMENT_DIRBANKNZ_SORT_ORDER',
            'MODULE_PAYMENT_DIRBANKNZ_ACCNUM',
            'MODULE_PAYMENT_DIRBANKNZ_ACCNAM',
            'MODULE_PAYMENT_DIRBANKNZ_BANKNAM',
            'MODULE_PAYMENT_DIRBANKNZ_ORDER_STATUS_ID');

delete from CONFIGURATION  where configuration_key in (
            'MODULE_PAYMENT_DIRBANKNZ_STATUS',
            'MODULE_PAYMENT_DIRBANKNZ_ZONE',
            'MODULE_PAYMENT_DIRBANKNZ_SORT_ORDER',
            'MODULE_PAYMENT_DIRBANKNZ_ACCNUM',
            'MODULE_PAYMENT_DIRBANKNZ_ACCNAM',
            'MODULE_PAYMENT_DIRBANKNZ_BANKNAM',
            'MODULE_PAYMENT_DIRBANKNZ_ORDER_STATUS_ID');
