select * from CONFIGURATION  where configuration_key in (
'MODULE_PAYMENT_DIRBANKCA_STATUS',
'MODULE_PAYMENT_DIRBANKCA_ZONE',
'MODULE_PAYMENT_DIRBANKCA_SORT_ORDER',
'MODULE_PAYMENT_DIRBANKCA_INSTNUM',
'MODULE_PAYMENT_DIRBANKCA_TRANSIT',
'MODULE_PAYMENT_DIRBANKCA_ACCNAM',
'MODULE_PAYMENT_DIRBANKCA_ACCNUM',
'MODULE_PAYMENT_DIRBANKCA_ORDER_STATUS_ID'
);

delete from CONFIGURATION  where configuration_key in (
'MODULE_PAYMENT_DIRBANKCA_STATUS',
'MODULE_PAYMENT_DIRBANKCA_ZONE',
'MODULE_PAYMENT_DIRBANKCA_SORT_ORDER',
'MODULE_PAYMENT_DIRBANKCA_INSTNUM',
'MODULE_PAYMENT_DIRBANKCA_TRANSIT',
'MODULE_PAYMENT_DIRBANKCA_ACCNAM',
'MODULE_PAYMENT_DIRBANKCA_ACCNUM',
'MODULE_PAYMENT_DIRBANKCA_ORDER_STATUS_ID'
);